// $REMOVE_START$
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

/**
 * @note @warn DO NOT EDIT THIS FILE. IT IS TEMPLATE CODE.
 */
// $REMOVE_END$

/**
 * $LAYER_NAME$
 */
import { StandardLayer, StandardLayerProps } from '@polaris.gl/gsi'

import type { PropDescription } from '../../private/schema/layers'

/**
 * $LAYER_NAME$ Props
 */

type $LAYER_NAME$Props = StandardLayerProps & {
	// 🔨 your stuffs
}

/**
 * $LAYER_NAME$ Class
 */

class $LAYER_NAME$ extends StandardLayer {
	name = '$LAYER_NAME$' as const

	constructor(props: $LAYER_NAME$Props) {
		super(props)

		// 🔨 your stuffs
	}

	// 🔨 your stuffs
}

export function create$LAYER_NAME$(props: ConstructorParameters<typeof $LAYER_NAME$>[0]) {
	return new $LAYER_NAME$(props)
}

/**
 * Props Description. Used to generate the props editer UI.
 */
export const propsDesc = [] as PropDescription[]
